Wgraham/impose grouplayer reordering 2
brainglobe/napari-experimental pull request #26
Opened 2024-06-28 11:30 UTC by willGraham01

Before submitting a pull request (PR), please read the [contributing guide](https://github.com/brainglobe/.github/blob/main/CONTRIBUTING.md).

Please fill out as much of this template as you can, but if you have any problems or questions, just leave a comment and we will help out :)

## Description

**What is this PR**

- [ ] Bug fix
- [ ] Addition of a new feature
- [ ] Other

**Why is this PR needed?**

**What does this PR do?**

## References

Please reference any existing issues/PRs that relate to this PR.

## How has this PR been tested?

Please explain how any new code has been tested, and how you have ensured that no existing functionality has changed.

## Is this a breaking change?

If this PR breaks any existing functionality, please explain how and why.

## Does this PR require an update to the documentation?

If any features have changed, or have been added. Please explain how the documentation has been updated (and link to the associated PR). See [here](https://brainglobe.info/community/developers/index.html#to-improve-the-documentation) for details.

## Checklist:

- [ ] The code has been tested locally
- [ ] Tests have been added to cover all new functionality (unit & integration)
- [ ] The documentation has been updated to reflect any changes
- [ ] The code has been formatted with [pre-commit](https://pre-commit.com/)

2024-06-28 14:33 UTC, K-Meech approved these changes
Looks good! :tada:
Might be worth adding some quick tests to cover `_new_layer_in_main_viewer` and `on_layer_moved`?

2024-07-02 14:36 UTC, willGraham01 commented
Have added a short test for the synchronisation of layers - everything in here will likely go though if the plugin eventually replaces the main layer viewer :cry: But for the time being we can be assured that things are sync-ing each time there's a change.

2024-07-04 09:17 UTC, K-Meech requested changes
Looks good! Found one other `strict` to remove for the 3.9 tests to pass

2024-07-04 09:17 UTC, K-Meech commented on tests/test_group_layer_widget.py
> +        strict=True,
I think `strict` was only introduced in 3.10, so you'll probably have to remove it to get the tests to pass with 3.9

2024-07-05 09:43 UTC, K-Meech approved these changes
Looks good :tada:

2024-07-05 09:44 UTC, merged